/**
 * components/MobileNav.tsx — MOBILE NAVIGATION (Hamburger Menu)
 *
 * ⚠️  "use client" required: uses `usePathname()` hook (same reason as Sidebar.tsx)
 *
 * WHY A SEPARATE MOBILE NAV?
 * The desktop Sidebar (Sidebar.tsx) is hidden on small screens (max-sm:hidden).
 * On mobile, we need a different UX — a slide-out drawer triggered by a hamburger
 * icon. This component handles that.
 *
 * HOW IT WORKS (user flow):
 *   1. User taps the ☰ hamburger icon in the Navbar
 *   2. A Sheet (drawer) slides in from the left
 *   3. User taps a navigation link
 *   4. SheetClose wraps each link — clicking automatically closes the drawer
 *   5. Next.js Link navigates to the new page
 *
 * WHAT IS A "SHEET"?
 * Sheet is a Shadcn UI component — a panel that slides in from an edge (top/bottom/left/right).
 * It uses Radix UI under the hood for accessibility (focus trapping, ARIA, keyboard nav).
 * Imported from @/components/ui/sheet (generated by `npx shadcn@latest add sheet`).
 */

"use client"; // Required: uses usePathname() hook

import React from "react";

// Shadcn Sheet component — the slide-out drawer
import {
  Sheet,          // Root component (manages open/close state internally)
  SheetClose,     // Wraps content that should close the Sheet when clicked
  SheetContent,   // The sliding panel itself
  SheetTrigger,   // The element that opens the Sheet when clicked/tapped
} from "@/components/ui/sheet";

import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation"; // To detect the active route
import { sidebarLinks } from "@/constants";    // Same nav data as desktop Sidebar
import { cn } from "@/lib/utils";              // Conditional class merger

const MobileNav = () => {
  // Get current URL path to highlight the active link
  const pathname = usePathname();

  return (
    // `max-w-[264px]` caps the section width to match desktop sidebar width
    <section className="w-full max-w-[264px]">

      {/*
        <Sheet> manages the open/closed state of the drawer internally.
        You don't need useState here — Sheet handles it for you!
      */}
      <Sheet>

        {/*
          SheetTrigger — the element that OPENS the drawer.
          `render` prop accepts the JSX to render as the trigger element.
          `sm:hidden` → Only visible on small screens; desktop uses the sidebar instead.
        */}
        <SheetTrigger
          render={
            <button className="cursor-pointer sm:hidden">
              <Image
                src="/icons/hamburger.svg"
                width={36}
                height={36}
                alt="Open navigation menu"
              />
            </button>
          }
        />

        {/*
          SheetContent — the actual drawer panel that slides in.
          `side="left"` → slides in from the left edge of the screen.
          `border-none`  → remove default border
          `bg-dark-1`    → match our dark sidebar color (#1c1f2e)
        */}
        <SheetContent side="left" className="border-none bg-dark-1">

          {/* ── LOGO at top of drawer ──────────────────────────────────────── */}
          <Link href="/" className="flex items-center gap-1 ">
            <Image
              src="/icons/logo.svg"
              width={32}
              height={32}
              alt="Yoom logo"
              className="max-sm:size-10"
            />
            {/* Hidden on very small screens — icon alone is enough */}
            <p className="text-[26px] font-extrabold text-white max-sm:hidden">
              Yoom
            </p>
          </Link>

          {/*
            Main scrollable area for navigation links.
            `h-[calc(100vh-72px)]` → Full height minus the logo area (~72px)
            `overflow-y-auto`      → Add scroll if there are many links
          */}
          <div className="flex h-[calc(100vh-72px)] flex-col justify-between overflow-y-auto">
            <section className="flex h-full flex-col gap-6 pt-16 text-white">

              {/*
                Same .map() pattern as Sidebar.tsx — iterate over sidebarLinks
                and render each one as a nav link.
              */}
              {sidebarLinks.map((link) => {
                /**
                 * ACTIVE STATE
                 * In MobileNav we use exact match only (pathname === link.route).
                 * No `startsWith` here because clicking a link closes the drawer
                 * immediately via SheetClose, so sub-route highlighting isn't needed.
                 */
                const isActive = pathname === link.route;

                return (
                  /**
                   * SheetClose — KEY CONCEPT
                   * Wraps each nav link. When the user clicks the link:
                   *   1. SheetClose fires → drawer closes
                   *   2. Link navigates → new page loads
                   * Without SheetClose, the drawer would stay open after navigation.
                   *
                   * `nativeButton={false}` → Don't render SheetClose as a <button>.
                   *   We're rendering a <Link> inside it, so we don't want nested buttons.
                   * `render` prop → The actual element to render (our Link).
                   */
                  <SheetClose
                    key={link.label}
                    nativeButton={false}
                    render={
                      <Link
                        href={link.route}
                        className={cn(
                          // Base styles for every link
                          "flex gap-4 items-center p-4 rounded-lg w-full max-w-60",
                          {
                            // Blue background highlight for the active link
                            "bg-blue-1": isActive,
                          },
                        )}
                      >
                        {/* Navigation icon */}
                        <Image
                          src={link.imgUrl}
                          alt={link.label}
                          width={20}
                          height={20}
                        />
                        {/* Link label text */}
                        <p className="font-semibold">{link.label}</p>
                      </Link>
                    }
                  />
                );
              })}
            </section>
          </div>
        </SheetContent>
      </Sheet>
    </section>
  );
};

export default MobileNav;
